FROM golang:alpine as builder
# install git and build zapconnect
RUN apk update && \
    apk upgrade && \
    apk add git

RUN go get -d github.com/LN-Zap/zapconnect  
RUN echo $GOPATH
RUN cd $GOPATH/src/github.com/LN-Zap/zapconnect && go get ./... && go install -v ./...

FROM guggero/lnd as lnd-bin

FROM guggero/lnd-unlocker as final

COPY --from=lnd-bin /bin/lncli /bin/
COPY --from=lnd-bin /bin/lnd /bin/
COPY --from=builder /go/bin/zapconnect /bin/

